language: go
go:
  - 1.9.x
  - 1.10.x
  - master
os:
  - linux
matrix:
 fast_finish: true
 allow_failures:
   - go: master

sudo: false

notifications:
  email:
    recipients:
      - laurent.aphecetche@cern.ch
      - binet@cern.ch
    on_success: change
    on_failure: always
