language: go
go:
  - 1.12.x
os:
  - linux
matrix:
 fast_finish: true
 allow_failures:
   - go: master

services:
  - docker

after_success:
  - docker build -t mrrtf/mch-mapping-api .
  - docker images

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin

deploy:
  provider: script
  script: docker push mrrtf/mch-mapping-api
  on:
    branch:
      - master

notifications:
  email:
    recipients:
      - laurent.aphecetche@cern.ch
      - binet@cern.ch
    on_success: change
    on_failure: always

